remote_theme: mmistakes/minimal-mistakes
title: "Travel | “The World is a book, and those who do not travel read only a page.” – Saint Augustine"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
