title: "Travel | “The World is a book, and those who do not travel read only a page.” – Saint Augustine"
excerpt_separator: <!--more-->
collections:
  category:
    output: true
    permalink: /:collection/:name
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
